using System.Text.Json;
using System.Text.Encodings.Web;
using VisualQa.Core;
namespace VisualQa.Reporting;
public sealed class JsonReportWriter { public void Write(QaReport report,string path)=>File.WriteAllText(path,JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true})); }
public sealed class HtmlReportWriter {
 public void Write(QaReport report,string path) {
  var rows=string.Join("",report.Findings.Select(Row));
  var images=string.Join("",report.Artifacts.Where(x=>x.Key.EndsWith(".png",StringComparison.OrdinalIgnoreCase)).Select(x=>$"<figure><figcaption>{E(x.Key)}</figcaption><img src='{E(x.Value)}' alt='{E(x.Key)}'></figure>"));
  var counts=string.Join("",Enum.GetValues<QaStatus>().Select(s=>$"<span class='badge {s}'>{s}: {report.Findings.Count(x=>x.Status==s)}</span>"));
  File.WriteAllText(path,$"<!doctype html><meta charset='utf-8'><title>Visual QA report</title><style>body{{font:14px system-ui,sans-serif;margin:2rem;color:#17202a}}table{{border-collapse:collapse;width:100%;margin-top:1rem}}td,th{{border:1px solid #d7dde3;padding:.55rem;text-align:left;vertical-align:top}}th{{background:#f4f6f8}}.badge{{display:inline-block;margin:.15rem .3rem .15rem 0;padding:.25rem .5rem;border-radius:.25rem;background:#eef2f5}}.Fail,.Error{{color:#b00020;font-weight:600}}.Warning{{color:#8a5a00;font-weight:600}}.Pass{{color:#067d28;font-weight:600}}.NotEvaluated{{color:#586069}}code{{white-space:pre-wrap}}.empty{{color:#586069;font-style:italic}}img{{max-width:420px;border:1px solid #c7d0d9}}figure{{display:inline-block;vertical-align:top;margin:1rem 1rem 0 0}}figcaption{{font-weight:600;margin-bottom:.4rem}}.action{{min-width:16rem}}</style><h1>Visual QA: {E(report.Component)} / {E(report.Platform)}</h1><p>Overall result: <b class='{report.Status}'>{report.Status}</b>; structural similarity: <b>{report.Similarity:P2}</b>.</p><div>{counts}</div><div>{images}</div><table><tr><th>Rule</th><th>Element</th><th>Status</th><th>Expected</th><th>Actual</th><th>Difference</th><th>Evidence</th><th>Recommended action</th></tr>{rows}</table>");
 }
 static string Row(QaFinding x)=>$"<tr><td><code>{E(x.Rule)}</code></td><td>{V(x.ElementId)}</td><td class='{x.Status}'>{x.Status}</td><td>{V(x.Expected)}</td><td>{V(x.Actual)}</td><td>{V(x.Delta)}</td><td>{E(x.Message)}</td><td class='action'>{E(Action(x))}</td></tr>";
 static string V(object? value)=>value is null?"<span class='empty'>Not supplied</span>":$"<code>{E(Convert.ToString(value))}</code>";
 static string Action(QaFinding x) { if(x.Status==QaStatus.Pass)return "No action required."; if(x.Status==QaStatus.NotEvaluated)return x.Rule.Contains("lineHeight",StringComparison.OrdinalIgnoreCase)||x.Rule.Contains("letterSpacing",StringComparison.OrdinalIgnoreCase)?"Expose this typography value from WPF when available; otherwise leave it unavailable.":"Add a stable VisualQa.Id and capture the required runtime property; do not infer it."; if(x.Rule.StartsWith("geometry.",StringComparison.Ordinal))return "Adjust the WPF layout/template so rendered bounds match the design tolerance."; if(x.Rule.StartsWith("typography.",StringComparison.Ordinal))return "Adjust the WPF text style, font resource, or text content to match Figma."; if(x.Rule.StartsWith("color.",StringComparison.Ordinal))return "Adjust the resolved WPF brush/token and recapture the same state."; if(x.Rule.StartsWith("perceptual.",StringComparison.Ordinal)||x.Rule.StartsWith("pixel.",StringComparison.Ordinal))return "Inspect overlay/heatmap/diff regions, correct the visible WPF state, then recapture."; if(x.Rule.StartsWith("structural.",StringComparison.Ordinal))return "Add or align stable QA IDs for meaningful component, text, or icon elements."; return "Review expected and actual evidence, correct WPF, then recapture."; }
 static string E(string? s)=>HtmlEncoder.Default.Encode(s??"");
}
