namespace VisualQa.Core;

public static class ArtifactSchema { public const int CurrentVersion = 1; public static void Require(int version) { if (version != CurrentVersion) throw new InvalidDataException($"Unsupported schemaVersion '{version}'. Expected {CurrentVersion}."); } }
public enum QaStatus { Pass, Warning, Fail, NotEvaluated, Error }
public sealed record RectSpec(double X, double Y, double Width, double Height) { public double Right => X + Width; public double Bottom => Y + Height; }
public sealed record ThicknessSpec(double Top, double Right, double Bottom, double Left) { public static readonly ThicknessSpec Zero = new(0,0,0,0); }
public sealed record EnvironmentInfo(string Os, string Runtime, double? ScaleFactor = null, string? Renderer = null, IReadOnlyList<string>? Fonts = null);
public sealed class DesignComponentSpec { public int SchemaVersion { get; init; } = ArtifactSchema.CurrentVersion; public string Name { get; init; } = ""; public double? Width { get; init; } public double? Height { get; init; } public IReadOnlyList<DesignElementSpec> Elements { get; init; } = []; }
public sealed class DesignElementSpec { public string Id { get; init; } = ""; public string Name { get; init; } = ""; public string? Type { get; init; } public string? Role { get; init; } public RectSpec? Bounds { get; init; } public string? Text { get; init; } public string? FontFamily { get; init; } public double? FontSize { get; init; } public double? LineHeight { get; init; } public double? LetterSpacing { get; init; } public string? FontWeight { get; init; } public string? ForegroundColor { get; init; } public string? BackgroundColor { get; init; } public string? IconName { get; init; } public Dictionary<string,double> NumericTokens { get; init; } = []; public Dictionary<string,string> SemanticTokens { get; init; } = []; }
public sealed class RuntimeComponentSnapshot { public int SchemaVersion { get; init; } = ArtifactSchema.CurrentVersion; public string Name { get; init; } = ""; public string Platform { get; init; } = ""; public double Width { get; init; } public double Height { get; init; } public double DpiX { get; init; } = 96; public double DpiY { get; init; } = 96; public EnvironmentInfo? Environment { get; init; } public IReadOnlyList<RuntimeElementSnapshot> Elements { get; init; } = []; }
public sealed class RuntimeElementSnapshot { public string Id { get; init; } = ""; public string Type { get; init; } = ""; public string? Role { get; init; } public RectSpec Bounds { get; init; } = new(0,0,0,0); public string? Text { get; init; } public string? FontFamily { get; init; } public double? FontSize { get; init; } public double? LineHeight { get; init; } public double? LetterSpacing { get; init; } public string? FontWeight { get; init; } public string? ForegroundColor { get; init; } public string? BackgroundColor { get; init; } public string? IconName { get; init; } public ThicknessSpec Margin { get; init; } = ThicknessSpec.Zero; public ThicknessSpec Padding { get; init; } = ThicknessSpec.Zero; public bool IsVisible { get; init; } = true; }
public sealed class QaFinding { public string Rule { get; init; } = ""; public QaStatus Status { get; init; } public string? ElementId { get; init; } public object? Expected { get; init; } public object? Actual { get; init; } public double? Delta { get; init; } public string Message { get; init; } = ""; }
public sealed class QaReport { public string Component { get; init; } = ""; public string Platform { get; init; } = ""; public QaStatus Status { get; init; } public double? Similarity { get; init; } public IReadOnlyList<QaFinding> Findings { get; init; } = []; public Dictionary<string,string> Artifacts { get; init; } = []; }
