namespace VisualQa.Core;

public sealed record QaTolerances(double Position = 1, double Size = 1, double Spacing = 1, double DeltaEPass = 1.5, double DeltaEWarning = 3);
public interface IQaValidator { IEnumerable<QaFinding> Validate(DesignComponentSpec design, RuntimeComponentSnapshot runtime, QaTolerances tolerances); }
/// <summary>Limits metadata assertions to design elements that can be represented by a runtime UI tree.
/// Figma vector/path implementation layers remain covered by the screenshot comparison.</summary>
public static class ComparableElements {
 public static IEnumerable<DesignElementSpec> From(DesignComponentSpec design) => design.Elements.Where(IsComparable);
 public static bool IsComparable(DesignElementSpec element) => element.Role is not null || element.Text is not null || element.IconName is not null;
}
public static class ElementMatcher {
 public static RuntimeElementSnapshot? Match(DesignElementSpec d, IEnumerable<RuntimeElementSnapshot> all) => all.FirstOrDefault(x => x.Id == d.Id) ?? all.FirstOrDefault(x => Same(x.Id,d.Name)) ?? all.FirstOrDefault(x => d.Role is not null && x.Role == d.Role) ?? all.FirstOrDefault(x => d.Text is not null && x.Text == d.Text && IsTextElement(x)) ?? all.Where(x => x.Type == d.Type && d.Bounds is not null).OrderBy(x => Math.Abs(x.Bounds.X-d.Bounds!.X)+Math.Abs(x.Bounds.Y-d.Bounds!.Y)).FirstOrDefault();
 static bool IsTextElement(RuntimeElementSnapshot element) => element.Type.Contains("text", StringComparison.OrdinalIgnoreCase) || element.Type.Contains("label", StringComparison.OrdinalIgnoreCase);
 static bool Same(string a,string b) => string.Equals(Normalize(a), Normalize(b), StringComparison.Ordinal); static string Normalize(string value) => value.Replace("-", "").Replace("_", "").Replace(" ", "").ToLowerInvariant(); }
public sealed class ComponentGeometryValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d, RuntimeComponentSnapshot r, QaTolerances t) { if (d.Width is not null) yield return GeometryValidator.Find("component.width", "component-root", d.Width.Value, r.Width, t.Size); if (d.Height is not null) yield return GeometryValidator.Find("component.height", "component-root", d.Height.Value, r.Height, t.Size); } }
public sealed class GeometryValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d, RuntimeComponentSnapshot r,QaTolerances t) { foreach(var e in ComparableElements.From(d)) { var a=ElementMatcher.Match(e,r.Elements); if(e.Bounds is null || a is null) { yield return Missing("geometry",e.Id); continue; } foreach(var p in new[]{("x",e.Bounds.X,a.Bounds.X,t.Position),("y",e.Bounds.Y,a.Bounds.Y,t.Position),("width",e.Bounds.Width,a.Bounds.Width,t.Size),("height",e.Bounds.Height,a.Bounds.Height,t.Size)}) yield return Find("geometry."+p.Item1,e.Id,p.Item2,p.Item3,p.Item4); }} static QaFinding Missing(string r,string id)=>new(){Rule=r,ElementId=id,Status=QaStatus.NotEvaluated,Message="Expected bounds or matched runtime element is unavailable."}; internal static QaFinding Find(string rule,string id,double expected,double actual,double tolerance)=>new(){Rule=rule,ElementId=id,Expected=expected,Actual=actual,Delta=actual-expected,Status=Math.Abs(actual-expected)<=tolerance?QaStatus.Pass:QaStatus.Fail,Message=$"Expected {expected:0.##}, actual {actual:0.##}."}; }
public sealed class TypographyValidator : IQaValidator { readonly IReadOnlyDictionary<string,string> fontFamilyAliases; public TypographyValidator(IReadOnlyDictionary<string,string>? fontFamilyAliases=null)=>this.fontFamilyAliases=fontFamilyAliases??new Dictionary<string,string>(StringComparer.Ordinal); public IEnumerable<QaFinding> Validate(DesignComponentSpec d,RuntimeComponentSnapshot r,QaTolerances t) { foreach(var e in ComparableElements.From(d)){var a=ElementMatcher.Match(e,r.Elements); if(e.FontFamily is not null) yield return FontFamilyFinding(e.Id,e.FontFamily,a?.FontFamily); foreach(var p in new[]{("fontWeight",e.FontWeight,a?.FontWeight),("text",e.Text,a?.Text)}.Where(p=>p.Item2 is not null)) yield return StringFinding("typography."+p.Item1,e.Id,p.Item2,p.Item3); foreach(var p in new[]{("fontSize",e.FontSize,a?.FontSize),("lineHeight",e.LineHeight,a?.LineHeight),("letterSpacing",e.LetterSpacing,a?.LetterSpacing)}.Where(p=>p.Item2 is not null)) yield return p.Item3 is null?Not("typography."+p.Item1,e.Id):GeometryValidator.Find("typography."+p.Item1,e.Id,p.Item2!.Value,p.Item3.Value,t.Size); }} QaFinding FontFamilyFinding(string id,string expected,string? actual){if(actual is null)return Not("typography.fontFamily",id);var normalized=fontFamilyAliases.TryGetValue(actual,out var alias)?alias:actual;var aliasNote=string.Equals(actual,normalized,StringComparison.Ordinal)?string.Empty:$" Normalized to '{normalized}' by configured font-family alias.";return new(){Rule="typography.fontFamily",ElementId=id,Expected=expected,Actual=actual,Status=string.Equals(expected,normalized,StringComparison.Ordinal)?QaStatus.Pass:QaStatus.Fail,Message=$"Expected '{expected}', actual '{actual}'.{aliasNote}"};} internal static QaFinding StringFinding(string rule,string id,string? expected,string? actual){if(expected is null||actual is null)return Not(rule,id);if(rule.EndsWith("fontWeight",StringComparison.Ordinal)) { expected=Weight(expected);actual=Weight(actual); }return new(){Rule=rule,ElementId=id,Expected=expected,Actual=actual,Status=expected==actual?QaStatus.Pass:QaStatus.Fail,Message=$"Expected '{expected}', actual '{actual}'."};} static string Weight(string value)=>value.Trim().ToLowerInvariant() switch{"thin"=>"100","extralight"=>"200","light"=>"300","normal" or "regular"=>"400","medium"=>"500","semibold" or "demibold"=>"600","bold"=>"700","extrabold"=>"800","black" or "heavy"=>"900",_=>value}; internal static QaFinding Not(string rule,string id)=>new(){Rule=rule,ElementId=id,Status=QaStatus.NotEvaluated,Message="Property is unavailable on one side."}; }
public sealed class ColorValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d, RuntimeComponentSnapshot r, QaTolerances t) { foreach (var e in ComparableElements.From(d)) { var a = ElementMatcher.Match(e, r.Elements); if (e.ForegroundColor is not null) yield return Find("color.foreground", e.Id, e.ForegroundColor, a?.ForegroundColor); if (e.BackgroundColor is not null) yield return Find("color.background", e.Id, e.BackgroundColor, a?.BackgroundColor); } } static QaFinding Find(string rule, string id, string expected, string? actual) => actual is null ? TypographyValidator.Not(rule, id) : new() { Rule=rule, ElementId=id, Expected=expected, Actual=actual, Status=string.Equals(expected, actual, StringComparison.OrdinalIgnoreCase) ? QaStatus.Pass : QaStatus.Fail, Message=$"Expected '{expected}', actual '{actual}'." }; }
public sealed class AppearanceValidator : IQaValidator {
 public IEnumerable<QaFinding> Validate(DesignComponentSpec d, RuntimeComponentSnapshot r, QaTolerances t) {
  foreach(var e in ComparableElements.From(d)) foreach(var finding in Compare(e,ElementMatcher.Match(e,r.Elements),t)) yield return finding;
  var rootDesign=d.Elements.FirstOrDefault(x=>x.Bounds?.X==0&&x.Bounds?.Y==0&&x.Bounds.Width==d.Width&&x.Bounds.Height==d.Height);
  var rootRuntime=r.Elements.FirstOrDefault(x=>x.Id.EndsWith("-root",StringComparison.OrdinalIgnoreCase));
  if(rootDesign is not null&&rootRuntime is not null) foreach(var finding in Compare(rootDesign,rootRuntime,t,"component-root")) yield return finding;
 }
 static IEnumerable<QaFinding> Compare(DesignElementSpec e,RuntimeElementSnapshot? a,QaTolerances t,string? id=null) { var key=id??e.Id; if(e.BackgroundColor is not null)yield return Color("color.background",key,e.BackgroundColor,a?.BackgroundColor); if(e.BorderColor is not null)yield return Color("border.color",key,e.BorderColor,a?.BorderColor); if(e.BorderThickness is not null) foreach(var side in new[]{("top",e.BorderThickness.Top,a?.BorderThickness?.Top),("right",e.BorderThickness.Right,a?.BorderThickness?.Right),("bottom",e.BorderThickness.Bottom,a?.BorderThickness?.Bottom),("left",e.BorderThickness.Left,a?.BorderThickness?.Left)}) yield return Number("border.thickness."+side.Item1,key,side.Item2,side.Item3,t.Size); if(e.Padding is not null) foreach(var side in new[]{("top",e.Padding.Top,a?.Padding.Top),("right",e.Padding.Right,a?.Padding.Right),("bottom",e.Padding.Bottom,a?.Padding.Bottom),("left",e.Padding.Left,a?.Padding.Left)}) yield return Number("spacing.padding."+side.Item1,key,side.Item2,side.Item3,t.Spacing); if(e.CornerRadius is not null) foreach(var corner in new[]{("topLeft",EffectiveRadius(e,e.CornerRadius.TopLeft),a?.CornerRadius?.TopLeft),("topRight",EffectiveRadius(e,e.CornerRadius.TopRight),a?.CornerRadius?.TopRight),("bottomRight",EffectiveRadius(e,e.CornerRadius.BottomRight),a?.CornerRadius?.BottomRight),("bottomLeft",EffectiveRadius(e,e.CornerRadius.BottomLeft),a?.CornerRadius?.BottomLeft)}) yield return Number("shape.cornerRadius."+corner.Item1,key,corner.Item2,corner.Item3,t.Size); if(e.Opacity is not null)yield return Number("appearance.opacity",key,e.Opacity.Value,a?.Opacity,.01); if(e.TextAlignment is not null)yield return Text("layout.textAlignment",key,e.TextAlignment,a?.TextAlignment); if(e.FlowDirection is not null)yield return Text("layout.flowDirection",key,e.FlowDirection,a?.FlowDirection); if(e.TextWrapping is not null)yield return Text("layout.textWrapping",key,e.TextWrapping,a?.TextWrapping); if(e.TextTrimming is not null)yield return Text("layout.textTrimming",key,e.TextTrimming,a?.TextTrimming); if(e.IsClipped is not null)yield return Bool("layout.isClipped",key,e.IsClipped.Value,a?.IsClipped); if(e.IsVisible is not null)yield return Bool("visibility",key,e.IsVisible.Value,a?.IsVisible); }
 static double EffectiveRadius(DesignElementSpec element,double value) => element.Bounds is null ? value : Math.Min(value,Math.Min(element.Bounds.Width,element.Bounds.Height)/2d);
 static QaFinding Color(string rule,string id,string expected,string? actual)=>actual is null?TypographyValidator.Not(rule,id):new(){Rule=rule,ElementId=id,Expected=expected,Actual=actual,Status=string.Equals(expected,actual,StringComparison.OrdinalIgnoreCase)?QaStatus.Pass:QaStatus.Fail,Message=$"Expected '{expected}', actual '{actual}'."};
 static QaFinding Number(string rule,string id,double expected,double? actual,double tolerance)=>actual is null?TypographyValidator.Not(rule,id):GeometryValidator.Find(rule,id,expected,actual.Value,tolerance);
 static QaFinding Text(string rule,string id,string expected,string? actual)=>actual is null?TypographyValidator.Not(rule,id):new(){Rule=rule,ElementId=id,Expected=expected,Actual=actual,Status=string.Equals(expected,actual,StringComparison.OrdinalIgnoreCase)?QaStatus.Pass:QaStatus.Fail,Message=$"Expected '{expected}', actual '{actual}'."};
 static QaFinding Bool(string rule,string id,bool expected,bool? actual)=>actual is null?TypographyValidator.Not(rule,id):new(){Rule=rule,ElementId=id,Expected=expected,Actual=actual,Status=expected==actual.Value?QaStatus.Pass:QaStatus.Fail,Message=$"Expected '{expected}', actual '{actual}'."};
}
public sealed class IconValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d,RuntimeComponentSnapshot r,QaTolerances t) { foreach(var e in ComparableElements.From(d).Where(x=>x.IconName is not null)){var a=ElementMatcher.Match(e,r.Elements); yield return TypographyValidator.StringFinding("icon.metadata",e.Id,e.IconName,a?.IconName); } } }
public sealed class StructuralValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d,RuntimeComponentSnapshot r,QaTolerances t) { var comparable = ComparableElements.From(d).ToArray(); foreach(var e in comparable) if(ElementMatcher.Match(e,r.Elements) is null) yield return new(){Rule="structural.missing",ElementId=e.Id,Status=QaStatus.NotEvaluated,Message="No mapped runtime element is available; add a stable VisualQa.Id when this must be enforced."}; foreach(var e in r.Elements.Where(x=>!comparable.Any(y=>ElementMatcher.Match(y,[x]) is not null))) yield return new(){Rule="structural.extra",ElementId=e.Id,Status=QaStatus.Warning,Message="Runtime element has no mapped design match."}; } }
public sealed class SpacingValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d,RuntimeComponentSnapshot r,QaTolerances t) { foreach(var e in d.Elements){var a=ElementMatcher.Match(e,r.Elements); foreach(var token in e.NumericTokens.Where(x=>x.Key.EndsWith("/gap",StringComparison.OrdinalIgnoreCase))) { var otherId=token.Key.Split('/')[0]; var other=d.Elements.FirstOrDefault(x=>x.Id==otherId); var oa=other is null?null:ElementMatcher.Match(other,r.Elements); if(a is null||oa is null) yield return TypographyValidator.Not("spacing.gap",e.Id); else yield return GeometryValidator.Find("spacing.gap",e.Id,token.Value,a.Bounds.X-oa.Bounds.Right,t.Spacing); } } } }
public sealed class QaEvaluator { public QaStatus Evaluate(IEnumerable<QaFinding> findings,bool warningsBlock) => findings.Any(x=>x.Status is QaStatus.Fail or QaStatus.Error)?QaStatus.Fail: warningsBlock&&findings.Any(x=>x.Status==QaStatus.Warning)?QaStatus.Fail:findings.Any(x=>x.Status==QaStatus.Warning)?QaStatus.Warning:QaStatus.Pass; }
