namespace VisualQa.Core;

public sealed record QaTolerances(double Position = 1, double Size = 1, double Spacing = 1, double DeltaEPass = 1.5, double DeltaEWarning = 3);
public interface IQaValidator { IEnumerable<QaFinding> Validate(DesignComponentSpec design, RuntimeComponentSnapshot runtime, QaTolerances tolerances); }
public static class ElementMatcher {
 public static RuntimeElementSnapshot? Match(DesignElementSpec d, IEnumerable<RuntimeElementSnapshot> all) => all.FirstOrDefault(x => x.Id == d.Id) ?? all.FirstOrDefault(x => Same(x.Id,d.Name)) ?? all.FirstOrDefault(x => d.Role is not null && x.Role == d.Role) ?? all.FirstOrDefault(x => d.Text is not null && x.Text == d.Text) ?? all.Where(x => x.Type == d.Type && d.Bounds is not null).OrderBy(x => Math.Abs(x.Bounds.X-d.Bounds!.X)+Math.Abs(x.Bounds.Y-d.Bounds!.Y)).FirstOrDefault();
 static bool Same(string a,string b) => string.Equals(Normalize(a), Normalize(b), StringComparison.Ordinal); static string Normalize(string value) => value.Replace("-", "").Replace("_", "").Replace(" ", "").ToLowerInvariant(); }
public sealed class GeometryValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d, RuntimeComponentSnapshot r,QaTolerances t) { foreach(var e in d.Elements) { var a=ElementMatcher.Match(e,r.Elements); if(e.Bounds is null || a is null) { yield return Missing("geometry",e.Id); continue; } foreach(var p in new[]{("x",e.Bounds.X,a.Bounds.X,t.Position),("y",e.Bounds.Y,a.Bounds.Y,t.Position),("width",e.Bounds.Width,a.Bounds.Width,t.Size),("height",e.Bounds.Height,a.Bounds.Height,t.Size)}) yield return Find("geometry."+p.Item1,e.Id,p.Item2,p.Item3,p.Item4); }} static QaFinding Missing(string r,string id)=>new(){Rule=r,ElementId=id,Status=QaStatus.NotEvaluated,Message="Expected bounds or matched runtime element is unavailable."}; internal static QaFinding Find(string rule,string id,double expected,double actual,double tolerance)=>new(){Rule=rule,ElementId=id,Expected=expected,Actual=actual,Delta=actual-expected,Status=Math.Abs(actual-expected)<=tolerance?QaStatus.Pass:QaStatus.Fail,Message=$"Expected {expected:0.##}, actual {actual:0.##}."}; }
public sealed class TypographyValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d,RuntimeComponentSnapshot r,QaTolerances t) { foreach(var e in d.Elements){var a=ElementMatcher.Match(e,r.Elements); foreach(var p in new[]{("fontFamily",e.FontFamily,a?.FontFamily),("fontWeight",e.FontWeight,a?.FontWeight),("text",e.Text,a?.Text),("foreground",e.ForegroundColor,a?.ForegroundColor)}) yield return StringFinding("typography."+p.Item1,e.Id,p.Item2,p.Item3); foreach(var p in new[]{("fontSize",e.FontSize,a?.FontSize),("lineHeight",e.LineHeight,a?.LineHeight),("letterSpacing",e.LetterSpacing,a?.LetterSpacing)}) yield return p.Item2 is null||p.Item3 is null?Not("typography."+p.Item1,e.Id):GeometryValidator.Find("typography."+p.Item1,e.Id,p.Item2.Value,p.Item3.Value,t.Size); }} internal static QaFinding StringFinding(string rule,string id,string? expected,string? actual){if(expected is null||actual is null)return Not(rule,id);if(rule.EndsWith("fontWeight",StringComparison.Ordinal)) { expected=Weight(expected);actual=Weight(actual); }return new(){Rule=rule,ElementId=id,Expected=expected,Actual=actual,Status=expected==actual?QaStatus.Pass:QaStatus.Fail,Message=$"Expected '{expected}', actual '{actual}'."};} static string Weight(string value)=>value.Trim().ToLowerInvariant() switch{"thin"=>"100","extralight"=>"200","light"=>"300","normal" or "regular"=>"400","medium"=>"500","semibold" or "demibold"=>"600","bold"=>"700","extrabold"=>"800","black" or "heavy"=>"900",_=>value}; internal static QaFinding Not(string rule,string id)=>new(){Rule=rule,ElementId=id,Status=QaStatus.NotEvaluated,Message="Property is unavailable on one side."}; }
public sealed class IconValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d,RuntimeComponentSnapshot r,QaTolerances t) { foreach(var e in d.Elements.Where(x=>x.IconName is not null)){var a=ElementMatcher.Match(e,r.Elements); yield return TypographyValidator.StringFinding("icon.metadata",e.Id,e.IconName,a?.IconName); } } }
public sealed class StructuralValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d,RuntimeComponentSnapshot r,QaTolerances t) { foreach(var e in d.Elements) if(ElementMatcher.Match(e,r.Elements) is null) yield return new(){Rule="structural.missing",ElementId=e.Id,Status=QaStatus.Fail,Message="Required design element was not captured."}; foreach(var e in r.Elements.Where(x=>!d.Elements.Any(y=>ElementMatcher.Match(y,[x]) is not null))) yield return new(){Rule="structural.extra",ElementId=e.Id,Status=QaStatus.Warning,Message="Runtime element has no design match."}; } }
public sealed class SpacingValidator : IQaValidator { public IEnumerable<QaFinding> Validate(DesignComponentSpec d,RuntimeComponentSnapshot r,QaTolerances t) { foreach(var e in d.Elements){var a=ElementMatcher.Match(e,r.Elements); foreach(var token in e.NumericTokens.Where(x=>x.Key.EndsWith("/gap",StringComparison.OrdinalIgnoreCase))) { var otherId=token.Key.Split('/')[0]; var other=d.Elements.FirstOrDefault(x=>x.Id==otherId); var oa=other is null?null:ElementMatcher.Match(other,r.Elements); if(a is null||oa is null) yield return TypographyValidator.Not("spacing.gap",e.Id); else yield return GeometryValidator.Find("spacing.gap",e.Id,token.Value,a.Bounds.X-oa.Bounds.Right,t.Spacing); } } } }
public sealed class QaEvaluator { public QaStatus Evaluate(IEnumerable<QaFinding> findings,bool warningsBlock) => findings.Any(x=>x.Status is QaStatus.Fail or QaStatus.Error)?QaStatus.Fail: warningsBlock&&findings.Any(x=>x.Status==QaStatus.Warning)?QaStatus.Fail:findings.Any(x=>x.Status==QaStatus.Warning)?QaStatus.Warning:QaStatus.Pass; }
